import { render, screen, fireEvent, waitFor } from '@testing-library/react'
import { vi } from 'vitest'
import { PromptEditor } from './PromptEditor'

// Mock data
const mockProject = {
  id: 'project-1',
  name: 'Test Project',
  description: 'A test project',
  currentVersion: 1,
  config: {
    systemLimits: {
      maxTokens: 4000,
      temperature: 0.7,
      model: 'gpt-4-turbo-preview',
      responseFormat: 'markdown',
      timeout: 30,
      retryAttempts: 3
    },
    outputRequirements: {
      format: { type: 'structured', schema: {} },
      constraints: [],
      examples: [],
      validation: { required: [], optional: [] }
    },
    testData: []
  },
  metadata: {
    createdAt: new Date(),
    updatedAt: new Date(),
    tags: [],
    category: 'other'
  }
}

const mockVersion = {
  id: 'version-1',
  projectId: 'project-1',
  versionNumber: 1,
  content: '# Test Prompt\n\nThis is a test prompt content.',
  timestamp: new Date(),
  description: 'Initial version',
  autoGenerated: false,
  metadata: {
    lines: 3,
    characters: 45,
    words: 8,
    changeType: 'major' as const
  }
}

// Store mocks
const mockProjectStore = {
  currentProject: mockProject
}

const mockVersionStore = {
  currentVersion: mockVersion,
  loadVersions: vi.fn(),
  isLoading: false
}

const mockEditorStore = {
  content: '# Test Prompt\n\nThis is a test prompt content.',
  setContent: vi.fn(),
  loadContent: vi.fn()
}

// Mock stores
vi.mock('@/lib/stores/projectStore', () => ({
  useProjectStore: () => mockProjectStore
}))

vi.mock('@/lib/stores/versionStore', () => ({
  useVersionStore: () => mockVersionStore
}))

vi.mock('@/lib/stores/editorStore', () => ({
  useEditorStore: () => mockEditorStore
}))

// Mock child components
vi.mock('./EditorToolbar', () => ({
  EditorToolbar: () => <div data-testid="editor-toolbar">Toolbar</div>
}))

vi.mock('./EditorStatusBar', () => ({
  EditorStatusBar: ({ content }: { content: string }) => (
    <div data-testid="editor-status-bar">
      Status: {content.length} chars
    </div>
  )
}))

describe('PromptEditor', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  describe('Rendering', () => {
    it('should render without crashing when project is selected', () => {
      render(<PromptEditor />)
      
      expect(screen.getByTestId('editor-toolbar')).toBeInTheDocument()
      expect(screen.getByTestId('editor-status-bar')).toBeInTheDocument()
      expect(screen.getByTestId('monaco-editor')).toBeInTheDocument()
    })

    it('should show no project selected message when no project', () => {
      // Mock no current project
      vi.mocked(mockProjectStore).currentProject = null
      
      render(<PromptEditor />)
      
      expect(screen.getByText('No project selected')).toBeInTheDocument()
      expect(screen.getByText('Create or select a project to start editing')).toBeInTheDocument()
    })

    it('should show loading state when versions are loading', () => {
      // Mock loading state
      vi.mocked(mockVersionStore).isLoading = true
      vi.mocked(mockVersionStore).currentVersion = null
      
      render(<PromptEditor />)
      
      expect(screen.getByText('Loading versions...')).toBeInTheDocument()
      expect(screen.getByRole('status')).toBeInTheDocument()
    })
  })

  describe('Monaco Editor Integration', () => {
    it('should display current content in editor', () => {
      render(<PromptEditor />)
      
      const editor = screen.getByTestId('monaco-editor')
      expect(editor).toHaveValue('# Test Prompt\n\nThis is a test prompt content.')
    })

    it('should call setContent when editor content changes', async () => {
      render(<PromptEditor />)
      
      const editor = screen.getByTestId('monaco-editor')
      fireEvent.change(editor, { target: { value: 'New content' } })
      
      expect(mockEditorStore.setContent).toHaveBeenCalledWith('New content')
    })

    it('should call loadContent when version changes', () => {
      render(<PromptEditor />)
      
      expect(mockEditorStore.loadContent).toHaveBeenCalledWith(mockVersion.content)
    })

    it('should clear editor when project has no versions', () => {
      // Mock no current version
      vi.mocked(mockVersionStore).currentVersion = null
      vi.mocked(mockVersionStore).isLoading = false
      
      render(<PromptEditor />)
      
      expect(mockEditorStore.loadContent).toHaveBeenCalledWith('')
    })
  })

  describe('Version Management', () => {
    it('should load versions when project changes', () => {
      render(<PromptEditor />)
      
      expect(mockVersionStore.loadVersions).toHaveBeenCalledWith('project-1')
    })

    it('should handle project change correctly', () => {
      const { rerender } = render(<PromptEditor />)
      
      // Change project
      const newProject = { ...mockProject, id: 'project-2', name: 'New Project' }
      vi.mocked(mockProjectStore).currentProject = newProject
      
      rerender(<PromptEditor />)
      
      expect(mockVersionStore.loadVersions).toHaveBeenCalledWith('project-2')
    })
  })

  describe('Editor Configuration', () => {
    it('should mount editor with correct options', () => {
      render(<PromptEditor />)
      
      const editor = screen.getByTestId('monaco-editor')
      
      // Check that editor receives focus when mounted
      fireEvent.focus(editor)
      
      // The onMount function should be called which sets editorRef
      expect(editor).toBeInTheDocument()
    })

    it('should use markdown language mode', () => {
      // This would typically be tested by checking Monaco editor configuration
      // Since we're mocking Monaco, we verify the component renders properly
      render(<PromptEditor />)
      
      expect(screen.getByTestId('monaco-editor')).toBeInTheDocument()
    })
  })

  describe('Component Layout', () => {
    it('should render toolbar at the top', () => {
      render(<PromptEditor />)
      
      const toolbar = screen.getByTestId('editor-toolbar')
      const editor = screen.getByTestId('monaco-editor')
      
      expect(toolbar).toBeInTheDocument()
      expect(editor).toBeInTheDocument()
    })

    it('should render status bar at the bottom with content info', () => {
      render(<PromptEditor />)
      
      const statusBar = screen.getByTestId('editor-status-bar')
      expect(statusBar).toHaveTextContent('Status: 45 chars')
    })

    it('should have proper flex layout structure', () => {
      const { container } = render(<PromptEditor />)
      
      // Check that main container has flex column layout
      const mainContainer = container.firstChild
      expect(mainContainer).toHaveClass('flex', 'flex-col', 'h-full')
    })
  })

  describe('Edge Cases', () => {
    it('should handle undefined content gracefully', () => {
      // Mock undefined content
      vi.mocked(mockEditorStore).content = undefined as any
      
      render(<PromptEditor />)
      
      // Should not crash and editor should handle undefined
      expect(screen.getByTestId('monaco-editor')).toBeInTheDocument()
    })

    it('should handle version without content', () => {
      // Mock version without content
      const versionWithoutContent = { ...mockVersion, content: '' }
      vi.mocked(mockVersionStore).currentVersion = versionWithoutContent
      
      render(<PromptEditor />)
      
      expect(mockEditorStore.loadContent).toHaveBeenCalledWith('')
    })

    it('should handle rapid project switching', () => {
      const { rerender } = render(<PromptEditor />)
      
      // Rapidly switch projects
      vi.mocked(mockProjectStore).currentProject = { ...mockProject, id: 'project-2' }
      rerender(<PromptEditor />)
      
      vi.mocked(mockProjectStore).currentProject = { ...mockProject, id: 'project-3' }
      rerender(<PromptEditor />)
      
      // Should call loadVersions for each project
      expect(mockVersionStore.loadVersions).toHaveBeenCalledWith('project-2')
      expect(mockVersionStore.loadVersions).toHaveBeenCalledWith('project-3')
    })
  })

  describe('Accessibility', () => {
    it('should have proper ARIA roles and labels', () => {
      render(<PromptEditor />)
      
      // Loading state should have status role
      vi.mocked(mockVersionStore).isLoading = true
      vi.mocked(mockVersionStore).currentVersion = null
      
      const { rerender } = render(<PromptEditor />)
      rerender(<PromptEditor />)
      
      expect(screen.getByRole('status')).toBeInTheDocument()
    })

    it('should provide meaningful no-project state message', () => {
      vi.mocked(mockProjectStore).currentProject = null
      
      render(<PromptEditor />)
      
      expect(screen.getByText('No project selected')).toBeInTheDocument()
      expect(screen.getByText('Create or select a project to start editing')).toBeInTheDocument()
    })
  })
})