export interface Folder {
  id: string
  name: string
  parentId?: string  // 支持嵌套文件夹
  collapsed: boolean // 折叠状态
  createdAt: Date
  updatedAt: Date
}

export interface Project {
  id: string
  name: string
  description?: string
  folderId?: string  // 所属文件夹 ID
  currentVersion: number
  config: ProjectConfig
  metadata: {
    createdAt: Date
    updatedAt: Date
    tags: string[]
    category: 'strategy' | 'analysis' | 'signal' | 'other'
  }
}

export interface Version {
  id: string
  projectId: string
  versionNumber: number
  content: string
  timestamp: Date
  description?: string
  autoGenerated: boolean
  metadata: {
    lines: number
    characters: number
    words: number
    changeType: 'minor' | 'major' | 'patch'
    diff?: {
      additions: number
      deletions: number
      modifications: number
    }
  }
  tags?: string[]
  parentVersion?: string
}

export interface ProjectConfig {
  systemLimits: SystemLimits
  outputRequirements: OutputRequirements
  testData: TestData[]
}

export interface SystemLimits {
  maxTokens: number
  temperature: number
  model: string
  responseFormat: 'text' | 'json' | 'markdown'
  timeout: number
  retryAttempts: number
}

export interface OutputRequirements {
  format: {
    type: 'structured' | 'narrative' | 'mixed'
    schema?: object
  }
  constraints: string[]
  examples: string[]
  validation: {
    required: string[]
    optional: string[]
  }
}

export interface TestData {
  id: string
  name: string
  input: {
    market: string
    signals: any[]
    context: object
  }
  expectedOutput?: string
  tags: string[]
}

export interface AnalysisResult {
  issues: AnalysisIssue[]
  score: {
    clarity: number
    completeness: number
    consistency: number
    overall: number
  }
  metrics: {
    complexity: number
    tokenUsage: number
    estimatedCost: number
  }
}

export interface AnalysisIssue {
  type: 'error' | 'warning' | 'info'
  category: string
  message: string
  line?: number
  suggestion?: string
  severity: 1 | 2 | 3
}

export interface OptimizationSuggestion {
  id: string
  type: 'clarity' | 'structure' | 'performance' | 'specialization'
  title: string
  description: string
  impact: 'low' | 'medium' | 'high'
  changes: string[]
  preview?: string
}

export interface ProjectStructure {
  version: string
  folders: LocalFolder[]
  projectMappings: Record<string, string | null>  // 旧格式: projectName -> folderId (保持向后兼容)
  projectIdMappings?: Record<string, { folderId: string | null; fsName: string }> // projectId -> { folderId, fsName }
  fsNameToProjectId?: Record<string, string>  // 文件系统名称 -> 项目ID (关键：用于名称不匹配时查找)
  versionDescriptions?: Record<string, Record<number, string>> // projectName -> { versionNumber: description }
  lastUpdated: string
  lastModified?: string // 本地文件最后修改时间
}

export interface LocalFolder {
  id: string
  name: string
  parentId?: string | null
}